Feat/profile
ArashAzma/Crypto-App pull request #8
Opened 2023-12-01 14:36 UTC by ArashAzma

2023-12-02 14:16 UTC, SMhdAsadi commented on components/UserName.tsx
> +  const lastName = useSelector(settings$.user.lastName);
یک نکته این وسط وجود داره.
هوک useSelector برای ساخت یک مقدار از روی **چندتا** observable هست. در شرایط خاصی که این چندتا بشه یکی، ما می‌تونیم خود observable رو به عنوان ورودی بهش بدیم.
انقدر با useSelector مستقیما observable رو تبدیل به value کردیم که فراموش کردیم میشه چندتا observable رو با هم ترکیب کرد.

یه ایرادی که این تیکه از کدت داره اینه که دو تا useSelector زده شده. احتمالا زمانی که firstname و lastname عوض بشن این دو بار رندر میشه.
برای رفع این مشکل میشه فقط از یک useSelector استفاده کرد و یه تابع بهش داد:
```ts
  const name = useSelector(() => {
    const firstName = settings$.user.firstName.get();
    const lastName = settings$.user.lastName.get();

    return `${firstName} ${lastName}`;
  });
```
این طوری دیگه تنها زمانی رندر مجدد میشه که خروجی تابعی که به useSelector دادیم تغییر کنه.

2023-12-02 14:20 UTC, SMhdAsadi commented on components/UserName.tsx
> +  const style = props.style;
```ts
const {style} = props;
```

2023-12-02 14:28 UTC, SMhdAsadi commented on screens/ProfileChangeScreen.tsx
> +function ProfileChangeScreen() {
هرچی جلوتر میری کامنت‌هایی که می‌زنی بهتر و بهتر میشه.
این کامیت رو با کامیت اولی که فکر می‌کنم یه برنچ شده بود مقایسه کن :)
ولی خب هنوزم جا برای بهتر شدن کامیت‌ها هست. مثلا توی این کامیت هم داری تایپ navigation رو اصلاح می‌کنی و هم داری یه صفحه اولیه از ProfileChange اضافه می‌کنی. اگه به عنوان کامیتت هم دقت کنی می‌بینی یه and داره.
این دو تا کار رو میشه مستقل از هم در نظر گرفت و دو تا کامیت مجزا براش زد. این طوری مستقل‌تر میشن.

2023-12-03 05:30 UTC, SMhdAsadi commented on components/Button.tsx
> +  const {onPress, title} = props;
اگه فقط به این دوتا prop از ButtonProps احتیاج داری، به نظرم نیازی نیست که تایپ props رو ButtonProps بذاری. مشکل این روش اینه که کسی که می‌خواد از این کامپوننت استفاده کنه کلی prop می‌تونه پاس بده در صورتی که فقط همین دوتا کار می‌کنن.
به نظرم تایپ props رو اینطوری تغییر بدی بهتره:

```ts
function Button(props: Pick<ButtonProps, 'onPress' | 'title'>) {
```

2023-12-03 05:53 UTC, SMhdAsadi commented on components/RadioButton.tsx
> +  selectedId: ObservablePrimitiveBaseFns<NonNullable<Gender>>;
کامپوننتی که زدی اسمش RadioButton هست. خیلی عمومیه. یکم غیر منطقیه اگه selectedId رو فقط Gender در نظر بگیریم.
یا تایپ Gender رو بردار و عمومی ترش کن تا این کامپوننت رو جاهای دیگه هم بشه استفاده کرد.
یا اسم این کامپوننت رو خاص کن. مثلا GenderRadioButton که دقیق مشخص کنه ورودیش از این نوع هست.

2023-12-03 05:56 UTC, SMhdAsadi commented on components/UserName.tsx
> +  const {style, showLabel} = props;
و اینجا بهش مقدار اولشه دلخواه بدی. مثلا showLabel پیش‌فرض false باشه. فقط در صورتی که بخواد label رو نشون بده باید پراپ showLabel رو استفاده کنه.

2023-12-03 05:59 UTC, SMhdAsadi commented on screens/ProfileChangeScreen.tsx
> +  });
این get هایی که استفاده کردی با این که داخل useObservable هستن ولی تغییرشون باعث نمیشه اینجا تغییری بکنه و دوباره اجرا بشه.
به عبارت دیگه دارن عین peek عمل می‌کنن. برای این که قاطی نشه به نظرم از peek استفاده کن.

2023-12-03 06:03 UTC, SMhdAsadi commented on components/TextField.tsx
> +  const [text, setText] = useState(value);
به جای این کارا می‌تونی از defaultValue استفاده کنی. اونطوری دیگه useState هم لازم نیست.

2023-12-03 06:05 UTC, SMhdAsadi commented on components/RadioButtonOption.tsx
> +type RadioButtonProps = {selected: boolean; onPress: () => void; label: string};
rename `selected` to `isSelected`

2023-12-03 06:09 UTC, SMhdAsadi commented
پکیج expo-dev-client رو به پروژه اضافه کن. این طوری دیگه به expo-go نیازی نیست.

2023-12-03 06:21 UTC, SMhdAsadi requested changes
دور اول ریویو تمام شد. خسته نباشی داوش :)

2023-12-06 15:05 UTC, ArashAzma commented on components/UserName.tsx
> +  const style = props.style;
تو کامیتای بعدی اصلاح شده ممنون

2023-12-06 15:06 UTC, ArashAzma commented on screens/ProfileChangeScreen.tsx
> +function ProfileChangeScreen() {
درست میگید ، اصلاح میکنم از این به بعد
حقیقتا یادم رفت کامیتش کنم برای همین دوتا شد

2023-12-06 15:08 UTC, ArashAzma commented on components/UserName.tsx
> +  const lastName = useSelector(settings$.user.lastName);
اصلاح شد 
خیلی ممنون

2023-12-06 15:10 UTC, ArashAzma commented on components/Button.tsx
> +  const {onPress, title} = props;
درست میگید اصلاح شد

2023-12-06 15:14 UTC, ArashAzma commented on components/UserName.tsx
> +  const {style, showLabel} = props;
اصلاح شد ممنون

2023-12-06 15:37 UTC, ArashAzma commented on components/RadioButtonOption.tsx
> +type RadioButtonProps = {selected: boolean; onPress: () => void; label: string};
done

2023-12-06 15:51 UTC, ArashAzma commented on components/RadioGroup.tsx
> +    flexDirection: 'row',
بهش پراپ layout اضافه کردم که میتونه row و column باشه که دیفالت row گذاشتم
و اگه column باشه زیر هم میان همینطور که گفتید

2023-12-06 17:02 UTC, ArashAzma commented on components/RadioButton.tsx
> +  selectedId: ObservablePrimitiveBaseFns<NonNullable<Gender>>;
با generic درستش کردم ممنون

2023-12-07 10:50 UTC, ArashAzma commented on components/TextField.tsx
> +  const [text, setText] = useState(value);
اصلاح شد ممنون

2023-12-07 12:25 UTC, SMhdAsadi commented on components/TextField.tsx
> +        defaultValue={value}
اون value هم به نظرم defaultValue بشه بهتره که از بیرون کامپوننت هم بفهمیم مقدار پیش‌فرض رو فقط داره مشخص می‌کنه.

2023-12-07 12:30 UTC, ArashAzma commented on components/Button.tsx
> +function Button(props: Pick<ButtonProps, 'onPress' | 'title'>) {
درست میگید بهتر میشه خیلی

2023-12-07 12:35 UTC, SMhdAsadi approved these changes

2023-12-07 12:38 UTC, ArashAzma commented on components/TextField.tsx
> +        defaultValue={value}
done

2023-12-09 06:37 UTC, AradSharafi commented on screens/ProfileChangeScreen.tsx
> +      <View style={styles.bodyContainer}>
اسم bodyContainer خوبه ولی content هم داشته باش :)

نیازی به اصلاح نیست

2023-12-09 06:37 UTC, AradSharafi commented on components/TextField.tsx
> +  const {autoFocus = false, showIcon, debouncedText$, ...rest} = props;
آرش من نیازی نمیبینم که جدا بشه 
چون autoFocus پیش فرض false و داخل rest هم false 

https://reactnative.dev/docs/textinput#autofocus

2023-12-09 06:37 UTC, AradSharafi commented on components/RadioGroup.tsx
> +      <View style={styles.container}>
اینجا جاهاشون رو برعکس کن 
یعنی اول view بعد computed

2023-12-09 06:52 UTC, ArashAzma commented on screens/ProfileChangeScreen.tsx
> +      <View style={styles.bodyContainer}>
ممنون خیلی بهتره

2023-12-09 06:59 UTC, ArashAzma commented on components/TextField.tsx
> +  const {autoFocus = false, showIcon, debouncedText$, ...rest} = props;
حذف کردم 
بهتر شد

2023-12-09 07:01 UTC, ArashAzma commented on components/RadioGroup.tsx
> +      <View style={styles.container}>
اصلاح شد

2023-12-09 07:02 UTC, merged